"""Add back is_private column to todos table

Revision ID: 4721333d9e8c
Revises: 64520991b6c8
Create Date: 2025-07-06 22:57:59.410778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4721333d9e8c'
down_revision: Union[str, Sequence[str], None] = '64520991b6c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add is_private column as nullable first
    op.add_column('todos', sa.Column('is_private', sa.Boolean(), nullable=True))
    
    # Convert visibility values to is_private values
    # 'private' -> is_private = True
    # 'team_session' or 'global_public' -> is_private = False
    op.execute("UPDATE todos SET is_private = TRUE WHERE visibility = 'private'")
    op.execute("UPDATE todos SET is_private = FALSE WHERE visibility IN ('team_session', 'global_public')")
    
    # Make is_private non-nullable with default value
    op.alter_column('todos', 'is_private', nullable=False, server_default='true')
    
    # Drop the visibility column
    op.drop_column('todos', 'visibility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add visibility column back
    op.add_column('todos', sa.Column('visibility', sa.VARCHAR(), nullable=True))
    
    # Convert is_private values back to visibility values
    # is_private = True -> 'private'
    # is_private = False and is_global_public = True -> 'global_public'
    # is_private = False and is_global_public = False -> 'team_session'
    op.execute("UPDATE todos SET visibility = 'private' WHERE is_private = TRUE")
    op.execute("UPDATE todos SET visibility = 'global_public' WHERE is_private = FALSE AND is_global_public = TRUE")
    op.execute("UPDATE todos SET visibility = 'team_session' WHERE is_private = FALSE AND is_global_public = FALSE")
    
    # Make visibility non-nullable with default
    op.alter_column('todos', 'visibility', nullable=False, server_default="'private'")
    
    # Drop is_private column
    op.drop_column('todos', 'is_private')
    # ### end Alembic commands ###
